# Generated by Django 4.1 on 2022-09-01 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_skills', to=settings.AUTH_USER_MODEL)),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_id', to='users.skills')),
            ],
        ),
    ]
