# Generated by Django 4.0.2 on 2022-09-03 03:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CSS/HTML', 'CSS/HTML'), ('Python', 'Python'), ('DJANGO/DRF', 'DJANGO/DRF'), ('JavaScript/ReactJS', 'JavaScript/ReactJS')], max_length=45, null=True),
        ),
    ]
