# Generated by Django 4.0.2 on 2022-09-06 03:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mentorskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='years_industry_experience',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CSS/HTML', 'CSS/HTML'), ('Python', 'Python'), ('DJANGO/DRF', 'DJANGO/DRF'), ('JavaScript/ReactJS', 'JavaScript/ReactJS')], max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='MentorSkills',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
