# Generated by Django 4.0.2 on 2022-09-06 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_skills'),
        ('users', '0005_remove_customuser_years_industry_experience_and_more'),
    ]

    operations = [
    ]
